global:
  external_labels:
    monitor: codelab-monitor
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - labels:
      alias: relay-node-1
      type: cardano-node
    targets:
    - relay-node-1:12798