version: '3.4'
services:
  relay-node-1:
    image: cardano-node-docker
    container_name: cardano-node
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - ./relay-node-1/db:/usr/local/cardano/db
      - ./config:/usr/local/cardano/config
    environment: 
      - PROMETHEUS_HOST="0.0.0.0"
      - PROMETHEUS_PORT="12798"
      - HOST_ADDR="0.0.0.0"
      - NODE_PORT="3000"
      - NODE_NAME="relay-node-1"
      - NODE_RELAY="True"
    expose:
      - 12798
      - 3000
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    user: root
    volumes:
      - ./prom/config:/etc/prometheus
      - ./prom/data:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=48h'
    expose:
      - 9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 80:3000

