{
 "title": "Cardano: Application metrics v2",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cardano Last Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_ChainDB_blockNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_byron_proxy_ChainDB_blockNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_ChainDB_slotNum_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Chain Density",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_ChainDB_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_ChainDB_epoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot leading share (% of slots led)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "sum(rate(cardano_node_metrics_Forge_node_is_leader_int[710s])/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s]))",
     "legendFormat": "Total led slots"
    }
   ]
  },
  {
   "title": "Rejected blocks since last restart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int - cardano_node_metrics_Forge_adopted_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "cardano_node_metrics_ChainDB_slotInEpoch_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Current KES Period",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(avg(cardano_node_ChainDB_metrics_slotNum_int{alias=~\"c-.*\"})/3600)"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_ChainDB_metrics_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(cardano_node_metrics_ChainDB_blockNum_int[150s])*60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node RSS (allocated memory in RAM, in MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(cardano_node_metrics_Forge_forge_about_to_lead_int[710s])",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "CPU Utilization (1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time()-node_boot_time_seconds)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Memory Available (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cardano Service Restarts Per Hour",
   "type": "graph",
   "description": "Shows how many times cardano related services have been restarted within a 1 hour lookback window",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(increase(node_systemd_unit_state{name=~\"cardano.*|byron.*|explorer.*\",state=\"active\"}[1h:10s])) > 0",
     "legendFormat": "{{alias}}-{{name}}"
    }
   ]
  },
  {
   "title": "Node Memory Free (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s])) * 8",
     "legendFormat": "Aggregate cluster ingress (received)"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8)",
     "legendFormat": "Aggregate cluster egress (transmit)"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}